sudo: required
language: generic
services:
  - docker
  
before-install:
  - docker build -t javiersolsona/react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true javiersolsona/react npm run test