sudo: required
language: generic
services:
  - docker
  
before-install:
  - docker build -t javiersolsona/dokcer-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true javiersolsona/dokcer-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-727461847258"
  bucket_path: "docker react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY    